{
 "title": "Celeborn",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "baseLegend", "label": "baseLegend", "query": "__auto" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_WorkerCount_Value",
     "type": "timeseries",
     "description": "The count of active workers.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "metrics_WorkerCount_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_RegisteredShuffleCount_Value",
     "type": "timeseries",
     "description": "The count of registered shuffle.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "metrics_RegisteredShuffleCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornTotalBytes_Value",
     "type": "timeseries",
     "description": "Celeborn total device capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornTotalBytes_Value{role=\"Master\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornFreeBytes_Value",
     "type": "timeseries",
     "description": "Celeborn total device free capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornFreeBytes_Value{role=\"Master\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RunningApplicationCount_Value",
     "type": "timeseries",
     "description": "The count of running applications.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "metrics_RunningApplicationCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_IsActiveMaster_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "metrics_IsActiveMaster_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_PartitionSize_Value",
     "type": "timeseries",
     "description": "The size of estimated shuffle partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_PartitionSize_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_ActiveShuffleSize_Value",
     "type": "timeseries",
     "description": "The active shuffle size of workers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleSize_Value{role=\"Master\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleFileCount_Value",
     "type": "timeseries",
     "description": "The active shuffle file count of workers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleFileCount_Value{role=\"Master\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OfferSlotsTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_OfferSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OfferSlotsTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_LostWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in lost list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "metrics_LostWorkerCount_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_ExcludedWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in excluded list.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "metrics_ExcludedWorkerCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ShutdownWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in shutdown list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "metrics_ShutdownWorkerCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DecommissionWorkerCount_Value",
     "type": "timeseries",
     "description": "The count of workers in decommission list.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "metrics_DecommissionWorkerCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SlotsAllocated_increase_1h",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "increase(metrics_SlotsAllocated_Count[1h])",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_ReserveSlotsTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_ReserveSlotsTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_PausePushData_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      { "expr": "metrics_PausePushData_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicate_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicate_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushDataTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PausePushDataTime_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PausePushDataAndReplicateTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PausePushDataAndReplicateTime_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleSize_Value",
     "type": "timeseries",
     "description": "The active shuffle size of a worker including master replica and slave replica.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleSize_Value{role=\"Worker\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveShuffleFileCount_Value",
     "type": "timeseries",
     "description": "The active shuffle file count of a worker including master replica and slave replica.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "metrics_ActiveShuffleFileCount_Value{role=\"Worker\"}",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveConnectionCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "metrics_ActiveConnectionCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_IsDecommissioningWorker_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "metrics_IsDecommissioningWorker_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveSlotsCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      { "expr": "metrics_ActiveSlotsCount_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_CleanTaskQueueSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "metrics_CleanTaskQueueSize_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_CleanExpiredShuffleKeysTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_CleanExpiredShuffleKeysTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_CleanExpiredShuffleKeysTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_CleanExpiredShuffleKeysTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "PushRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "metrics_WriteDataSuccessCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "metrics_WriteDataFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataWriteFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataWriteFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataCreateConnectionFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataCreateConnectionFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataConnectionExceptionCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataConnectionExceptionCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataTimeoutCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataTimeoutCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicateDataFailNonCriticalCauseCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "metrics_ReplicateDataFailNonCriticalCauseCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WriteDataHardSplitCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "expr": "metrics_WriteDataHardSplitCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "FetchRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_OpenStreamTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_OpenStreamTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_OpenStreamTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_FetchChunkTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FetchChunkTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_OpenStreamSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
     "targets": [
      {
       "expr": "metrics_OpenStreamSuccessCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_OpenStreamFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
     "targets": [
      {
       "expr": "metrics_OpenStreamFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkSuccessCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "metrics_FetchChunkSuccessCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_FetchChunkFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "targets": [
      {
       "expr": "metrics_FetchChunkFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ActiveChunkStreamCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "targets": [
      {
       "expr": "metrics_ActiveChunkStreamCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlushDataRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_TakeBufferTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_TakeBufferTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_TakeBufferTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_FlushDataTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_FlushDataTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_CommitFilesTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_CommitFilesTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_CommitFilesTime_Max", "legendFormat": "${baseLegend}" }
     ]
    }
   ]
  },
  {
   "title": "MemoryRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_NettyMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_NettyMemory_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "DirectMemoryUsageRatio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "metrics_DirectMemoryUsageRatio_Value"
      }
     ]
    },
    {
     "title": "MemoryFileStorageSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_MemoryFileStorageSize_Value"
      }
     ]
    },
    {
     "title": "MemoryStorageFileCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "metrics_MemoryStorageFileCount_Value"
      }
     ]
    },
    {
     "title": "metrics_DiskBuffer_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_DiskBuffer_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "EvictedFileCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      { "expr": "metrics_EvictedFileCount_Value" }
     ]
    },
    {
     "title": "metrics_push_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedHeapMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_push_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_push_usedDirectMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedHeapMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_fetch_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_fetch_usedDirectMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedHeapMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedHeapMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_replicate_usedDirectMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_replicate_usedDirectMemory_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ReadBufferAllocatedCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "metrics_ReadBufferAllocatedCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "BufferStreamReadBuffer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_BufferStreamReadBuffer_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ReadBufferDispatcherRequestsLength",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "metrics_ReadBufferDispatcherRequestsLength_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "SortRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_SortTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Mean", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_SortTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "metrics_SortTime_Max", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_SortingFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
     "targets": [
      { "expr": "metrics_SortingFiles_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_SortedFiles_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 238 },
     "targets": [
      { "expr": "metrics_SortedFiles_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_SortMemory_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_SortMemory_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_SortedFileSize_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
     "targets": [
      { "expr": "metrics_SortedFileSize_Value", "legendFormat": "${baseLegend}" }
     ]
    }
   ]
  },
  {
   "title": "CongestionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PotentialConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "metrics_PotentialConsumeSpeed_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_WorkerConsumeSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "metrics_WorkerConsumeSpeed_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_UserProduceSpeed_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      { "expr": "metrics_UserProduceSpeed_Value", "legendFormat": "${baseLegend}" }
     ]
    }
   ]
  },
  {
   "title": "MapPartitionRelatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 272 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryPushDataHandshakeTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaPushDataHandshakeTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaPushDataHandshakeTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionStartTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionStartTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionStartTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 308 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PrimaryRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 308 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_PrimaryRegionFinishTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Mean",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Mean",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_ReplicaRegionFinishTime_Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_ReplicaRegionFinishTime_Max",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_PushDataHandshakeFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 326 },
     "targets": [
      {
       "expr": "metrics_PushDataHandshakeFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 326 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_RegionStartFailCount_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
     "targets": [
      {
       "expr": "metrics_RegionStartFailCount_Count",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "Credit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "ActiveCreditStreamCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 343 },
     "targets": [
      {
       "expr": "metrics_ActiveCreditStreamCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "ActiveMapPartitionCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 343 },
     "targets": [
      {
       "expr": "metrics_ActiveMapPartitionCount_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_JVMCPUTime_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "metrics_JVMCPUTime_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_LastMinuteSystemLoad_Value",
     "type": "timeseries",
     "description": "The system load average for the last minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_LastMinuteSystemLoad_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceOSFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceOSFreeBytes_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_DeviceCelebornFreeBytes_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_DeviceCelebornFreeBytes_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    },
    {
     "title": "metrics_AvailableProcessors_Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 368 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_AvailableProcessors_Value",
       "legendFormat": "${baseLegend}"
      }
     ]
    }
   ]
  },
  {
   "title": "UserConsumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics_diskFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 377 },
     "targets": [
      { "expr": "metrics_diskFileCount_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_diskBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 377 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_diskBytesWritten_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_hdfsFileCount_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 386 },
     "targets": [
      { "expr": "metrics_hdfsFileCount_Value", "legendFormat": "${baseLegend}" }
     ]
    },
    {
     "title": "metrics_hdfsBytesWritten_Value",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "metrics_hdfsBytesWritten_Value", "legendFormat": "${baseLegend}" }
     ]
    }
   ]
  }
 ]
}