apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: celeborn-worker
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 100Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: emr-eks-karpenter-karpenter-node
  securityGroupSelectorTerms:
  - name: emr-eks-karpenter-node*
  subnetSelectorTerms:
  - tags:
      Name: emr-eks-karpenter-private*
  tags:
    InstanceType: celeborn-worker
  userData: |
    #!/bin/bash
    yum install -y nvme-cli
    mount_location="/mnt"
    mkdir -p $mount_location
    # Get list of EBS Drives
    DEVICES=$(sudo nvme list | grep 'Amazon EC2 NVMe Instance Storage' | awk '{ print $1 }')
    IDX=1
    for DEV in $DEVICES
    do
      sudo mkfs.xfs ${DEV}
      sudo mkdir -p ${mount_location}/disk${IDX}
      echo ${DEV} ${mount_location}/disk${IDX} xfs defaults,noatime 1 2 >> /etc/fstab
      IDX=$((${IDX} + 1))
    done
    sudo mount -a
