apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: celeborn-worker
spec:
  disruption:
    budgets:
    - nodes: 100%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 'Never'
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        NodeGroupType: CelebornWorker 
        provisioner: celeborn-worker
        type: karpenter
    spec:
      nodeClassRef:
        name: celeborn-worker
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-west-2a
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - i3en.2xlarge
  weight: 10