apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oss-pods
  namespace: oss 
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  - serviceaccounts
  - services
  - pods/log
  - pods
  - configmaps
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - deletecollection
  - patch
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - patch
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - patch
  - get
  - delete
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - patch
  - get
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - deletecollection
  - patch
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - watch
  - annotate
  - describe
  - edit
  - create
  - label
  - deletecollection
  - patch
  - get
  - delete
